### ISSUE TITLE
Correction to build.sh

### ISSUE THREAD

**Issue by ujayadev** [FiveTechSoft/mod_harbour#40]
1. In go.sh the line sudo apt-get install apache2-dev is missing, without this apxs does not operate.
2. In build.sh the line no. 24 ln -sf ~/mod_harbour/linux/mod_harbour.c mod_harbour.c should be
ln -sf ~/mod_harbour/mod_harbour.c mod_harbour.c  (it is not in linux directory)
3. In build.sh the line no. 27 ln -sf ~/mod_harbour/linux/apache.prg apache.prg should be
ln -sf ~/mod_harbour/apache.prg apache.prg
If we do not correct these, the package is not built properly and all symlink to  libharbour.so.3.2.0 refer to broken file.

4. In go.sh the lines
echo 'LoadModule harbour_module /usr/lib/apache2/modules/mod_harbour.so' | sudo tee -a /etc/apache2/apache2.conf > /dev/null
echo '<FilesMatch "\.(prg|hrb)$">' | sudo tee -a /etc/apache2/apache2.conf > /dev/null
Keeps on adding these lines into apache2.conf everytime go.sh is executed.

With these corrections, I was able to build libharbour.so.3.2.0 and the commands work correctly.

**Comment by FiveTechSoft** [comment]
go.sh is intended for installing mod_harbour and not for building it

build.sh is intended for building mod_harbour (you may install it without having to build it)

2. and 3. fixed.

go.sh should be executed just once. For updates, simply do: git pull

many thanks for your feedback

**Comment by ujayadev** [comment]
Many thanks for your immediate reply.

Please confirm if sudo apt-get install apache2-dev has been added to go.sh .(without this apxs does not operate.)

Warm regards,

Jayadev

**Comment by FiveTechSoft** [comment]
sudo apt-get install apache2-dev has been added to build.sh

apxs should not operate from go.sh

many thanks

**Comment by ujayadev** [comment]
>>sudo apt-get install apache2-dev has been added to build.sh
Thanks.

>>apxs should not operate from go.sh
That, I undersand.

Warm regards,




many thanks
